<?php

use Illuminate\Database\Seeder;
use App\User;

class TestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::create([
            'name' => 'Maryanto',
            'email' => 'maryanto@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301877077',
            'campus' => 'KMG',
            'major' => 'Teknik Informatika',
            'phone_number' => '082264110120',
            'line_id' => 'maryanto',
            'lnt_subject' => 'Java Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'Awesa',
            'email' => 'awesa@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301977077',
            'campus' => 'ALS',
            'major' => 'Sistem Infomrasi',
            'phone_number' => '08264112233',
            'line_id' => 'awesa',
            'lnt_subject' => 'Mobile Programming',
            'role' => 0,
            'schedule_id' => 2,
        ]);

        User::create([
            'name' => 'Sendo',
            'email' => 'sendo@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301899347',
            'campus' => 'KMG',
            'major' => 'Mobile Application Technology',
            'phone_number' => '082264110120',
            'line_id' => 'sendosendo',
            'lnt_subject' => 'Web Design',
            'role' => 0,
            'schedule_id' => 3,
        ]);

        User::create([
            'name' => 'Benny',
            'email' => 'benkhar@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301923813',
            'campus' => 'ALS',
            'major' => 'Teknik Industri',
            'phone_number' => '089645223499',
            'line_id' => 'bennykhar',
            'lnt_subject' => 'Web Programming',
            'role' => 0,
            'schedule_id' => 2,
        ]);

        User::create([
            'name' => 'A',
            'email' => 'maryanto1@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301877071',
            'campus' => 'KMG',
            'major' => 'Teknik Informatika',
            'phone_number' => '082264110120',
            'line_id' => 'maryanto',
            'lnt_subject' => 'Java Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'B',
            'email' => 'awesa1@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301977072',
            'campus' => 'ALS',
            'major' => 'Sistem Infomrasi',
            'phone_number' => '08264112233',
            'line_id' => 'awesa',
            'lnt_subject' => 'Mobile Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'C',
            'email' => 'sendo1@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301899343',
            'campus' => 'KMG',
            'major' => 'Mobile Application Technology',
            'phone_number' => '082264110120',
            'line_id' => 'sendosendo',
            'lnt_subject' => 'Web Design',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'D',
            'email' => 'benkhar1@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301923814',
            'campus' => 'ALS',
            'major' => 'Teknik Industri',
            'phone_number' => '089645223499',
            'line_id' => 'bennykhar',
            'lnt_subject' => 'Web Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'E',
            'email' => 'maryanto2@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301877075',
            'campus' => 'KMG',
            'major' => 'Teknik Informatika',
            'phone_number' => '082264110120',
            'line_id' => 'maryanto',
            'lnt_subject' => 'Java Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'F',
            'email' => 'awesa2@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301977076',
            'campus' => 'ALS',
            'major' => 'Sistem Infomrasi',
            'phone_number' => '08264112233',
            'line_id' => 'awesa',
            'lnt_subject' => 'Mobile Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'G',
            'email' => 'sendo2@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301899317',
            'campus' => 'KMG',
            'major' => 'Mobile Application Technology',
            'phone_number' => '082264110120',
            'line_id' => 'sendosendo',
            'lnt_subject' => 'Web Design',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'H',
            'email' => 'benkhar2@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301923818',
            'campus' => 'ALS',
            'major' => 'Teknik Industri',
            'phone_number' => '089645223499',
            'line_id' => 'bennykhar',
            'lnt_subject' => 'Web Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'I',
            'email' => 'maryanto3@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301877079',
            'campus' => 'KMG',
            'major' => 'Teknik Informatika',
            'phone_number' => '082264110120',
            'line_id' => 'maryanto',
            'lnt_subject' => 'Java Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'J',
            'email' => 'awesa3@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301977010',
            'campus' => 'ALS',
            'major' => 'Sistem Infomrasi',
            'phone_number' => '08264112233',
            'line_id' => 'awesa',
            'lnt_subject' => 'Mobile Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'K',
            'email' => 'sendo3@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301899311',
            'campus' => 'KMG',
            'major' => 'Mobile Application Technology',
            'phone_number' => '082264110120',
            'line_id' => 'sendosendo',
            'lnt_subject' => 'Web Design',
            'role' => 0,
            'schedule_id' => 1,
        ]);

        User::create([
            'name' => 'L',
            'email' => 'benkhar3@gmail.com',
            'password' => Hash::make('asdasdasd'),
            'gender' => 'Male',
            'address' => 'Jl. Rawa Belong',
            'city' => 'Jakarta Barat',
            'place_of_birth' => 'Batam',
            'date_of_birth' => '2002-02-02',
            'fyp_batch' => 1,
            'nim' => '2301923812',
            'campus' => 'ALS',
            'major' => 'Teknik Industri',
            'phone_number' => '089645223499',
            'line_id' => 'bennykhar',
            'lnt_subject' => 'Web Programming',
            'role' => 0,
            'schedule_id' => 1,
        ]);
    }
}
